system:
  random_seed: 8
note: ""
batch_size: 64
wandb:
  use: false
defaults:
  - optimizer: default
  - backbone: dinov3_vitb16
  - dataset: unreal_motion_capture
  - probe: regressor # regressor | efficient_probing
  - _self_
experiment_name: example_scenario
experiment_model: dinov3_vitb16
training:
  min_samples_per_object: 10
  eval_every_epochs: 1
  save_checkpoints: false
  num_workers: 4
output_dir: "results"
