_target_: evals.datasets.unreal_motion_capture.UnrealMotionCaptureTask
root: /shared/results/common/kargin/unreal_engine/dataset/probe-equivariance
image_size: 224
image_mean: imagenet
split_ratio: 0.90
test_ratio: 0.00
environments: null
modes: null
seed: ${system.random_seed}
name: unreal_motion_capture
